#!/usr/bin/env bash
# Bash script for transferring a file from a client to a server using scp.
# Accepts the following parameters:
# - PATH_TO_FILE: Path to the file to be transferred
# - IP: IP address of the server
# - USERNAME: Username for the scp connection
# - PATH_TO_SSH_KEY: Path to the SSH private key used by scp for authentication

if [ "$#" -lt 4 ]; then
  echo 'Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY'
else
  # Transfer the file using scp to the specified location on the server
  scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3"@"$2":~
fi
