#!/usr/bin/env bash
# Bash script to install the Nginx server on an Ubuntu Linux distribution.
# The installed server is configured to listen on port 80 (HTTP) for connections
# and serves a default page (index.html) on HTTP GET requests.

# Update package information
sudo apt-get update -y

# Install Nginx
sudo apt-get install nginx -y

# Create a default index.html page
echo 'Hello World!' > /var/www/html/index.html

# Restart the Nginx service
sudo service nginx restart
