#!/usr/bin/env bash
# Bash script to install and configure Nginx web server on Ubuntu

# Update package information
sudo apt-get update -y

# Install Nginx
sudo apt-get install nginx -y

# Create a default HTML file with "Hello World!"
echo "Hello World!" | sudo tee /var/www/html/index.html

# Restart Nginx (this is not using systemctl)
sudo /etc/init.d/nginx restart
