#!/usr/bin/env bash
# Install the Nginx package
sudo apt install nginx

# Edit the Nginx configuration file
sudo vim /etc/nginx/sites-available/default

# Add the following line to the configuration file:
add_header X-Served-By $hostname;

# Save the file and exit the editor

# Restart the Nginx service
sudo systemctl restart nginx
