#!/usr/bin/env bash
# This script performs a MySQL dump and creates a compressed archive of the backup

mysqldump -uroot -p"$1" --all-databases > backup.sql
tar -czf $(date +%d-%m-%Y).tar.gz backup.sql
