#!/usr/bin/env bash
# Bash script to restore the default server port for Nginx

# Create a symbolic link to the default Nginx site configuration
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

# Start the Nginx service
sudo service nginx start
