#!/usr/bin/env bash
# Bash script to loop through numbers from 1 to 10 using a while loop.

current_number=1

while [ $current_number -le 10 ]; do
    case $current_number in
        4)
            echo "4 and then bad luck from China"
            ;;
        9)
            echo "9 and then bad luck from Japan"
            ;;
        17)
            echo "17 and then bad luck from Italy"
            ;;
        *)
            echo $current_number
            ;;
    esac
    ((current_number++))
done
