#!/usr/bin/env bash

# This script customizes the DNS resolution on an Ubuntu server:
# 1. Sets localhost resolution to 127.0.0.2
# 2. Resolves facebook.com to 8.8.8.8

# Create a backup of the current hosts file
cp /etc/hosts ~/hosts.new

# Update the hosts file with the desired resolutions
echo "127.0.0.2 localhost" > ~/hosts.new
echo "8.8.8.8 facebook.com" >> ~/hosts.new

# Replace the original hosts file with the modified one
cp -f ~/hosts.new /etc/hosts
