#!/usr/bin/env bash
# Launching nginx as the user 'nginx' and adjusting the default port to 8080
pkill apache2  # Stop the Apache2 server if running
sed -i 's/80/8080/g' /etc/nginx/sites-available/default  # Change the default port to 8080
chmod 644 /etc/nginx/nginx.conf  # Adjust permissions for the nginx configuration file
sudo -u nginx service nginx restart  # Restart the nginx service as the user 'nginx'
